trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

resources:
  repositories:
    - repository: niveristand-custom-device-build-tools
      type:       github
      ref:        main
      endpoint:   nivs-custom-devices
      name:       ni/niveristand-custom-device-build-tools

stages:
  - template: azure-templates/stages.yml@niveristand-custom-device-build-tools
    parameters:
      lvVersionsToBuild:
        - version: '2026'
          bitness: '64bit'

      buildSteps:
          # Windows build steps should all follow this build step, since it builds an important dependency
        - projectLocation: 'Source\Core\Data Sharing Framework Core Build - Windows.lvproj'
          buildOperation: 'ExecuteBuildSpec'
          target: 'My Computer'
          buildSpec: 'Data Sharing Framework Core'

      releaseVersion: '26.5.0'
      buildOutputLocation: 'Source\Built'
      archiveLocation: '\\nirvana\Measurements\VeriStandAddons\data_sharing_framework_CD'
      repoName: 'niveristand-data-sharing-framework-custom-device'
      createNetCoreRepo: false

  - template: azure-templates/linux-stage.yml@niveristand-custom-device-build-tools
    parameters:
      lvVersionsToBuild:
        - version: '2026'
          bitness: '64bit'

      buildSteps:

      - id: 'data-sharing-framework-custom-device-debug-build'
        projectLocation: 'Source/Custom Device/Data Sharing Framework Custom Device.lvproj'
        buildOperation: 'ExecuteBuildSpec'
        target: 'My Computer'
        buildSpec: 'Configuration(Linux) Debug'
      
      - id: 'data-sharing-framework-custom-device-release-build'
        projectLocation: 'Source/Custom Device/Data Sharing Framework Custom Device.lvproj'
        buildOperation: 'ExecuteBuildSpec'
        target: 'My Computer'
        buildSpec: 'Configuration(Linux) Release'


      releaseVersion: '26.5.0'
      branch: 'main'
      debugBuild: 'no'
      buildOutputLocation: 'Built'
      archiveLocation: '\\nirvana\Measurements\VeriStandAddons\data_sharing_framework_CD'
      repoName: 'data-sharing-framework-custom-device'
