[archive]
build_output_dir = 'Source\Built'
archive_location = '\\nirvana\Measurements\VeriStandAddons\data_sharing_framework_CD'

[dependencies.local]
libraries = ['Source\Built\Core\{target}\DSF Core.lvlibp']
copy_location = 'Includes'

[projects.Core_windows]
path = 'Source\Core\Data Sharing Framework Core Build - Windows.lvproj'

[projects.Core_linux_x64]
path = 'source\Core\Data Sharing Framework Core Build - Linux RT.lvproj'

[projects.CD_windows]
path = 'Source\Custom Device\Data Sharing Framework Custom Device.lvproj'

[projects.CD_linuxRT_x64]
path = 'Source\Custom Device\Data Sharing Framework Custom Device Linux RT x64.lvproj'

[projects.ScriptingExamples_windows]
path = 'Source\Custom Device\Scripting Examples\Data Sharing Framework Scripting.lvproj'

[[build.steps]]
name = 'Data Sharing Framework Core - Windows'
type = 'lvBuildSpec'
project = '{Core_windows}'
target = 'My Computer'
build_spec = 'Data Sharing Framework Core'

[[build.steps]]
name = 'Data Sharing Framework Core - Linux RT x64'
type = 'lvBuildSpec'
project = '{Core_linux_x64}'
target = 'Linux RT x64'
build_spec = 'Data Sharing Framework Core'

[[build.steps]]
name = 'Data Sharing Framework Custom Device Configuration - Windows'
type = 'lvBuildSpec'
project = '{CD_windows}'
target = 'My Computer'
build_spec = 'Configuration Release'
dependency_target = 'Windows'

[[build.steps]]
name = 'Data Sharing Framework Custom Device Scripting API - Windows'
type = 'lvBuildSpec'
project = '{CD_windows}'
target = 'My Computer'
build_spec = 'Scripting API'
dependency_target = 'Windows'

[[build.steps]]
name = 'Data Sharing Framework Custom Device Scripting Examples - Windows'
type = 'lvBuildSpec'
project = '{ScriptingExamples_windows}'
target = 'My Computer'
build_spec = 'Scripting Examples'
dependency_target = 'Windows'

[[build.steps]]
name = 'Data Sharing Framework Custom Device Engine - Windows'
type = 'lvBuildSpec'
project = '{CD_windows}'
target = 'My Computer'
build_spec = 'Engine Release'
dependency_target = 'Windows'

[[build.steps]]
name = 'Data Sharing Framework Custom Device Engine - Linux RT x64'
type = 'lvBuildSpec'
project = '{CD_linuxRT_x64}'
target = 'Linux RT x64'
build_spec = 'Engine Release'
dependency_target = 'Linux_x64'

[[package]]
type = 'nipkg'
control_file = 'control_dsf_cd'
package_output_dir = 'Source\Built'

[package.payload_map]
'Source\\Built\\Custom Device' = 'documents\National Instruments\NI VeriStand {veristand_version}\Custom Devices\Data Sharing Framework'
'Source\\Built\\Errors' = 'ni-paths-NISHAREDDIR{nipaths_64_bitness_suffix}\Errors\English'

[[package]]
type = 'nipkg'
payload_dir = 'Source\Built\Scripting API'
install_destination = 'ni-paths-LV{veristand_version}DIR{nipaths_64_bitness_suffix}\vi.lib\addons\VeriStand Custom Device Scripting APIs\Data Sharing Framework'
control_file = 'control_dsf_scripting'
package_output_dir = 'Source\Built'

[[package]]
type = 'nipkg'
payload_dir = 'Source\Built\Scripting Examples'
install_destination = 'ni-paths-LV{veristand_version}DIR{nipaths_64_bitness_suffix}\examples\NI VeriStand Custom Devices\Data Sharing Framework'
control_file = 'control_dsf_examples'
package_output_dir = 'Source\Built'

[notification]
type = 'teams'
