[archive]
build_output_dir = 'Built'
archive_location = '\\nirvana\Measurements\VeriStandAddons\data_sharing_framework_CD'

[dependencies.local]
libraries = ['Built\Core\{target}\DSF Core.lvlibp']
copy_location = 'VeriStand\Data Sharing Custom Device\Source'

[projects.windows]
path = 'Core\Data Sharing Framework Core Build - Windows.lvproj'

[projects.pharlap]
path = 'Core\Data Sharing Framework Core Build - PharLap x86.lvproj'

[projects.linux_x64]
path = 'Core\Data Sharing Framework Core Build - Linux RT x64.lvproj'

[projects.CD_windows]
path = 'VeriStand\Data Sharing Custom Device\Source\Data Sharing Framework Custom Device.lvproj'

[projects.CD_pharlap]
path = 'VeriStand\Data Sharing Custom Device\Source\Data Sharing Framework Custom Device Pharlap.lvproj'

[projects.CD_linuxRT]
path = 'VeriStand\Data Sharing Custom Device\Source\Data Sharing Framework Custom Device Linux RT.lvproj'

[[build.steps]]
name = 'Data Sharing Framework Core - Windows'
type = 'lvBuildSpec'
project = '{windows}'
target = 'My Computer'
build_spec = 'Data Sharing Framework Core'

[[build.steps]]
name = 'Data Sharing Framework Core - Pharlap x86'
type = 'lvBuildSpec'
project = '{pharlap}'
target = 'Pharlap x86'
build_spec = 'Data Sharing Framework Core'

#[[build.steps]]
#name = 'Data Sharing Framework Core - Linux RT x64'
#type = 'lvBuildSpec'
#project = '{linux_x64}'
#target = 'Linux RT x64'
#build_spec = 'Data Sharing Framework Core'

[[build.steps]]
name = 'Data Sharing Framework Custom Device Configuration - Windows'
type = 'lvBuildSpec'
project = '{CD_windows}'
target = 'My Computer'
build_spec = 'Configuration Release'
dependency_target = 'win\\x86'

[[build.steps]]
name = 'Data Sharing Framework Custom Device Engine - Windows'
type = 'lvBuildSpec'
project = '{CD_windows}'
target = 'My Computer'
build_spec = 'Engine Release'
dependency_target = 'win\\x86'

[[build.steps]]
name = 'Data Sharing Framework Custom Device Engine - Pharlap x86'
type = 'lvBuildSpec'
project = '{CD_pharlap}'
target = 'RT PXI Target'
build_spec = 'Engine Release'
dependency_target = 'pharlap\\x86'

#[[build.steps]]
#name = 'Data Sharing Framework Custom Device Engine - Linux RT x64'
#type = 'lvBuildSpec'
#project = '{linux_x64}'
#target = 'Linux RT x64'
#build_spec = 'Engine Release'

[package]
type = 'nipkg'
payload_dir = 'Built\Core'
install_destination = 'documents\National Instruments\NI VeriStand {veristand_version}\Data Sharing Framework'
control_file = 'control_dsf_core_windows'
package_output_dir = 'Built'

[package]
type = 'nipkg'
payload_dir = 'Built\Custom Device'
install_destination = 'documents\National Instruments\NI VeriStand {veristand_version}\Data Sharing Framework'
control_file = 'control_dsf_cd_windows'
package_output_dir = 'Built'
