[archive]
build_output_dir = 'Built'
archive_location = '\\nirvana\Measurements\VeriStandAddons\data_sharing_framework_CD'

[projects.windows]
path = 'Core\Data Sharing Framework Core Build - Windows.lvproj'

[projects.pharlap]
path = 'Core\Data Sharing Framework Core Build - PharLap x86.lvproj'

[projects.linux_x64]
path = 'Core\Data Sharing Framework Core Build - Linux RT x64.lvproj'

[[build.steps]]
name = 'Data Sharing Framework Core - Windows'
type = 'lvBuildSpec'
project = '{windows}'
target = 'My Computer'
build_spec = 'Data Sharing Framework Core'

[[build.steps]]
name = 'Data Sharing Framework Core - Pharlap x86'
type = 'lvBuildSpec'
project = '{pharlap}'
target = 'Pharlap x86'
build_spec = 'Data Sharing Framework Core'

[[build.steps]]
name = 'Data Sharing Framework Core - Linux RT x64'
type = 'lvBuildSpec'
project = '{linux_x64}'
target = 'Linux RT x64'
build_spec = 'Data Sharing Framework Core'

[package]
type = 'nipkg'
payload_dir = 'Built'
install_destination = 'ProgramFiles_32\National Instruments\RT Images'
control_file = 'control_dsf_core_windows'
package_output_dir = 'Source\Built'
