[archive]
build_output_dir = 'Built'
archive_location = '\\nirvana\Measurements\VeriStandAddons\data_sharing_framework_CD'

[dependencies.local]
libraries = ['Built\Core\{target}\DSF Core.lvlibp']
copy_location = 'VeriStand\Data Sharing Custom Device\Source'

[projects.Core_windows]
path = 'Core\Data Sharing Framework Core Build - Windows.lvproj'

[projects.Core_pharlap]
path = 'Core\Data Sharing Framework Core Build - PharLap x86.lvproj'

[projects.Core_linux_arm]
path = 'Core\Data Sharing Framework Core Build - Linux RT ARM.lvproj'

[projects.Core_linux_x64]
path = 'Core\Data Sharing Framework Core Build - Linux RT.lvproj'

[projects.CD_windows]
path = 'VeriStand\Data Sharing Custom Device\Source\Data Sharing Framework Custom Device.lvproj'

[projects.CD_pharlap]
path = 'VeriStand\Data Sharing Custom Device\Source\Data Sharing Framework Custom Device Pharlap.lvproj'

[projects.CD_linuxRT_arm]
path = 'VeriStand\Data Sharing Custom Device\Source\Data Sharing Framework Custom Device Linux RT ARM.lvproj'

[projects.CD_linuxRT_x64]
path = 'VeriStand\Data Sharing Custom Device\Source\Data Sharing Framework Custom Device Linux RT x64.lvproj'

[projects.ScriptingExamples_windows]
path = 'VeriStand\Data Sharing Custom Device\Source\Scripting Examples\Data Sharing Framework Scripting.lvproj'

[[build.steps]]
name = 'Data Sharing Framework Core - Windows'
type = 'lvBuildSpec'
project = '{Core_windows}'
target = 'My Computer'
build_spec = 'Data Sharing Framework Core'

[[build.steps]]
name = 'Data Sharing Framework Custom Device Configuration - Windows'
type = 'lvBuildSpec'
project = '{CD_windows}'
target = 'My Computer'
build_spec = 'Configuration Release'
dependency_target = 'Windows'

[[build.steps]]
name = 'Data Sharing Framework Custom Device Scripting API - Windows'
type = 'lvBuildSpec'
project = '{CD_windows}'
target = 'My Computer'
build_spec = 'Scripting API'
dependency_target = 'Windows'

[[build.steps]]
name = 'Data Sharing Framework Custom Device Scripting Examples - Windows'
type = 'lvBuildSpec'
project = '{ScriptingExamples_windows}'
target = 'My Computer'
build_spec = 'Scripting Examples'
dependency_target = 'Windows'

[[build.steps]]
name = 'Data Sharing Framework Custom Device Engine - Windows'
type = 'lvBuildSpec'
project = '{CD_windows}'
target = 'My Computer'
build_spec = 'Engine Release'
dependency_target = 'Windows'

[[package]]
type = 'nipkg'
control_file = 'control_dsf_cd'
package_output_dir = 'Built'

[package.payload_map]
'Built\\Custom Device' = 'documents\National Instruments\NI VeriStand {veristand_version}\Custom Devices\Data Sharing Framework'
'Built\\Errors' = 'ni-paths-NISHAREDDIR\Errors\English'

[[package]]
type = 'nipkg'
control_file = 'control_dsf_scripting'
package_output_dir = 'Built'

[package.payload_map]
'Built\\Scripting API' = 'ni-paths-LV{veristand_version}DIR\vi.lib\addons\VeriStand Custom Device Scripting APIs\Data Sharing Framework'
'Built\\Scripting Examples' = 'ni-paths-LV{veristand_version}DIR\examples\NI VeriStand Custom Devices\Data Sharing Framework'